Controllers/ApuntesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;

namespace Presentacion.Controllers
{
    public class ApuntesController : Controller
    {
        // GET: Apuntes
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListarApuntes()
        {
            List<VentaApunte> lsitadoApuntes = VentaApunte.ListarApuntes();
            return View(lsitadoApuntes);
        }

        public ActionResult VentasApuntes()
        {
            return View();
        }
    }
}

Controllers/EscaneoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class EscaneoController : Controller
    {
        // GET: Escaneo
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult Inicio()
        //{
        //    N_Usuario usaurio = N_Usuario.ObtenerPorUsuario(Request.Form["Usuario"], Request.Form["Password"]);

        //    if (usaurio.IdUsuario != 0)
        //    {
        //        Session["Usuario"] = N_Usuario.Listar().Where(x => x.Email == usaurio.Email).FirstOrDefault();

        //        return RedirectToAction("Index", "Usuario");
        //    }
        //    else

        //    {
        //        return RedirectToAction("Error", "Home", new { message = " Usuario o Contraseña incorrecta" });

        //    }
        //}

        [HttpPost]
        public JsonResult Inicio()
        {
            Resultado resultado = new Resultado();

            try
            {
                Session["Usuario"] = N_Usuario.ObtenerPorUsuario(Request.Form["Usuario"].ToString(), Request.Form["Password"].ToString());

                resultado.EsCorrecto = true;
                resultado.Mensaje = "";

                return Json(resultado);

            }
            catch (Exception ex)
            {
                resultado.EsCorrecto = false;
                resultado.Mensaje = ex.Message;

                return Json(resultado);
            }

        }


        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Login", "Home");
        }
    }
}

Controllers/ProfesoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class ProfesoreController : Controller
    {
        // GET: Profesores
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult VentaApuntes()
        {
            return RedirectToAction("VentaApuntes","Apunte");
        }
    }
}

Views/Apuntes/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Views/Apuntes/ListarApuntes.cshtml
@model List<Negocio.VentaApunte>

<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <title>Centro Copiado - Listado de Apuntes</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

</head>

<body>
    <div class="card-header"><h1 class="text-lg-center">Listado de Apuntes Habilitados</h1></div>
    <br/><br/>
    <div class="container">
        <table id="table_id" class="display">
            <thead>
                <tr>
                    <th>ID Apunte</th>
                    <th>Titulo Apunte</th>
                    <th>Stock</th>
                    <th>Cantidad Hojas</th>
                    <th>Estado</th>
                    <th>Accion</th>
                </tr>

            </thead>

            <tbody>
                @foreach (Negocio.VentaApunte item in Model)
                {
                    <tr>
                        <td>@item.id_Apuntes</td>
                        <td>@item.tituloApunte</td>
                        <td>@item.stockApuntes</td>
                        <td>@item.cantHojas</td>
                        <td>@item.estadoApunte</td>
                        <td>@Html.ActionLink("Vender Apuntes", "VentasApuntes", "Apuntes", new { id = @item.id_Apuntes }, new { @class = "rounded - circle border - 0" })</td>
                    </tr>                    
            }
                </tbody>
            </table>
    </div>

    <script>
        $(document).ready(function () {
            $('#table_id').DataTable(
                {
                    paging: false,
                }                
            );
        });
    </script>

</body>

</html >

Views/Apuntes/VentasApuntes.cshtml
@model Negocio.VentaApunte

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Centro Copiado - Listado de Apuntes</title>
    
</head>

<body>

    @using (Html.BeginForm("Guardar", "Apuntes", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <div class="row" name="titularAltaClientes">
                <div class="col-lg-12">
                    <div class="page-header">
                        <p id="titulosAltaClientes">PANTALLA ALTA DE CLIENTES</p>
                    </div>
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="control-label col-md-2">
                    <label>Apellido</label>
                </div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">
                    <label>Nombre</label>
                </div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">
                    <label>DNI</label>
                </div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.dni, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dni, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">
                    <label>Domicilio</label>
                </div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.domicilio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.domicilio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">
                    <label>Email</label>
                </div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">
                    <label>Estado</label>
                </div>
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.status)
                        @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cargar Cliente" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Pagina Inicio (Home)", "Index", "Home", new { @class = "btn btn-success" })
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

Views/Escaneo/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Campus Virtual- Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/CCA/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/CCA/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bienvenido!</h1>
                                    </div>

                                    <form id="FrmLogin" class="user">
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user" id="txtUsuario" name="Usuario" aria-describedby="UsuiarioHelp" placeholder="Ingresa tu Usuario...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" id="txtClave" name="Password" placeholder="Ingresa tu Contraseña">
                                        </div>

                                        <div id="msgErrorLogin" class="card bg-warning text-white shadow" style="display:none">
                                            <div class="card-body">
                                                <div class="text-white small">
                                                    Usuario o contraseña incorrectos
                                                </div>
                                            </div>
                                        </div>
                                        <br />
                                        <div class="btn btn-primary btn-user btn-block" onclick="ValidarUsuario()">Ingresar</div>
                                    </form>

                                    <div class="text-center">
                                        <a class="small" href="#">Crear Cuenta</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->    
    <script src="~/CCA/vendor/jquery/jquery.min.js"></script>
    <script src="~/CCA/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/CCA/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/CCA/js/sb-admin-2.min.js"></script>
    <script src="~/Scripts/Login.js"></script>

</body>

</html>

Views/Profesores/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <script src="~/CCA/vendor/jquery/jquery.js"></script>



    <link href="~/CCA/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/CCA/css/sb-admin-2.min.css" rel="stylesheet">

    <script src="~/CCA/vendor/jquery/jquery.min.js"></script>
    <script src="~/CCA/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/CCA/vendor/jquery-easing/jquery.easing.min.js"></script>

    <script src="~/CCA/js/sb-admin-2.min.js"></script>

    <script src="~/CCA/vendor/chart.js/Chart.min.js"></script>



</head>
<body>
    
    @RenderBody()

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Usuario/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Centro de Copiado</title>
    <!-- Custom fonts for this template-->
    <link href="~/CCA/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/CCA/css/sb-admin-2.min.css" rel="stylesheet">

</head>
<body>

    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-print"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Centro de Copiado</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">
                
        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-user"></i>
                <span>Profesores</span>
            </a>
            
        </li>

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("ListarApuntes","Apuntes")">
                <i class="fas fa-fw fa-book-open"></i>
                <span>Apuntes</span>                
            </a>           
        </li>

        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-bookmark"></i>
                <span>Reservas</span>
            </a>            
        </li>

        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-book"></i>
                <span>Escaneo</span>
            </a>          
        </li>
      
        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-hand-holding-usd"></i>
                <span>Ventas</span>
            </a>         
        </li>
        
        <li class="nav-item">
            <a class="nav-link" href="~/Home/LogOut/">
                <i class="fas fa-fw fa-times"></i>
                <span>Cerrar Sessión</span>
            </a>
        </li>

        <!-- División -->
        <hr class="sidebar-divider d-none d-md-block">
    </ul>


    <!-- Bootstrap core JavaScript-->
        <script src="~/CCA/vendor/jquery/jquery.min.js"></script>
        <script src="~/CCA/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/CCA/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/CCA/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/CCA/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/CCA/js/demo/chart-area-demo.js"></script>
    <script src="~/CCA/js/demo/chart-pie-demo.js"></script>
</body>

</html>